# Generated by Django 5.1.3 on 2024-12-15 17:07

from django.db import migrations, models

def add_allowed_languages(apps, schema_editor):
    Language = apps.get_model('app', 'Language')
    ALLOWED_LANGS = [
        {'code': 'ar', 'name': 'ض'},
        {'code': 'ber', 'name': 'ⵣ'},
        {'code': 'en', 'name': 'EN'},
        {'code': 'fr', 'name': 'FR'},
        {'code': 'de', 'name': 'DE'},
        {'code': 'es', 'name': 'ES'},
        {'code': 'it', 'name': 'IT'},
        {'code': 'zh', 'name': '中文'},
        {'code': 'hi', 'name': 'हिंदी'},
        {'code': 'ja', 'name': '日本語'},
        {'code': 'ko', 'name': '한국어'},
        {'code': 'pt', 'name': 'PT'},
        {'code': 'ru', 'name': 'RU'},
    ]

    for lang in ALLOWED_LANGS:
        Language.objects.create(code=lang['code'], name=lang['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_language'),
    ]

    operations = [
        migrations.RunPython(add_allowed_languages),
    ]
